---
namespace: "neilcar"
name: "microk8s"
readme: "README.md"
version: "1.0.4"
authors:
  - "fhochleitner (https://github.com/fhochleitner)"
  - "ckaserer (https://github.com/ckaserer)"
dependencies:
  "community.general": "*"
license:
  - "MIT"
repository: "https://www.github.com/neilcar/ansible-role.microk8s"
...
